# Generated by Django 4.0.1 on 2022-02-08 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Порода')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Catordog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Вид животного')),
            ],
        ),
        migrations.CreateModel(
            name='Classification_pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/classification_pet/', verbose_name='Фото питомца')),
            ],
            options={
                'verbose_name': 'pet',
                'verbose_name_plural': 'pets',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Гендер')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Кличка питомца')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('description', models.TextField(verbose_name='Особые приметы')),
                ('image', models.ImageField(upload_to='media/userspets/', verbose_name='Фото питомца')),
                ('catordog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.catordog', verbose_name='Кошка или собака')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.gender', verbose_name='Пол питомца')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
    ]
