# Generated by Django 4.0.1 on 2022-02-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_classification_pet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classification_pet',
            options={'verbose_name': 'pet', 'verbose_name_plural': 'pets'},
        ),
        migrations.AddField(
            model_name='classification_pet',
            name='name',
            field=models.CharField(default=2, max_length=20, verbose_name='Гендер'),
            preserve_default=False,
        ),
    ]
