# Generated by Django 4.0.1 on 2022-02-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_classification_pet_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification_pet',
            name='name',
        ),
    ]
